# Generated by Django 5.2.1 on 2025-05-17 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfluencerFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_username', models.CharField(max_length=255)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='checker.influencer')),
            ],
            options={
                'unique_together': {('influencer', 'followed_username')},
            },
        ),
    ]
